[package]
name = "dash_spv_apple_bindings"
version = "0.4.15"
description = "C-bindings for using and interoperating with Dash SPV"
readme = "README.md"
edition = "2021"
build = "build.rs"
publish = true

[dependencies]
blake3 = "1.3.2"
dash-spv-masternode-processor = { path = "../dash-spv-masternode-processor" }
dash-spv-coinjoin = { path = "../dash-spv-coinjoin" }
ferment-interfaces = { path = "../../ferment/ferment-interfaces" }
ferment-macro = { path = "../../ferment/ferment-macro" }
#ferment-interfaces = { git = "https://github.com/pankcuf/ferment.git", package = "ferment-interfaces" }
#ferment-macro = { git = "https://github.com/pankcuf/ferment.git", package = "ferment-macro" }
rs-merk-verify-c-binding = { version = "0.1.3", git = "https://github.com/dashpay/rs-merk-verify-c-binding", branch = "for-use-in-main-crate" }
rs-x11-hash = "0.1.8"

[dev-dependencies]
libc = "0.2.146"
reqwest = { version = "0.11.18", features = ["blocking", "json"] }
serde = { version = "1.0.144", features = ["derive"] }
serde_json = "1.0.85"
dash-spv-masternode-processor = { path = "../dash-spv-masternode-processor", features = ["default", "test-helpers"] }
dash-spv-coinjoin = { path = "../dash-spv-coinjoin", features = ["test-helpers"] }

[build-dependencies]
cbindgen = "0.24.3"
ferment = { path = "../../ferment/ferment" }
#ferment = { git = "https://github.com/pankcuf/ferment.git", package = "ferment" }

[lib]
name = "dash_spv_apple_bindings"
crate-type = ["staticlib", "cdylib"]

#[profile.release]
#lto = "thin"
#opt-level = 3
#debug = true

