[package]
name = "dash_spv_apple_bindings"
version = "0.4.10"
description = "C-bindings for using and interoperating with Dash SPV"
readme = "README.md"
edition = "2021"
build = "build.rs"
publish = true

[dependencies]
blake3 = "1.3.2"
dash-spv-masternode-processor = { path = "../dash-spv-masternode-processor" }
rs-x11-hash = "0.1.8"
rs-ffi-interfaces = { git = "https://github.com/pankcuf/rs-ffi-macro.git", branch = "feat/unwrap-generics", package = "rs-ffi-interfaces" }
rs-ffi-macro-derive = { git = "https://github.com/pankcuf/rs-ffi-macro.git", branch = "feat/unwrap-generics", package = "rs-ffi-macro-derive" }
rs-merk-verify-c-binding = { version = "0.1.3", git = "https://github.com/dashpay/rs-merk-verify-c-binding", branch = "for-use-in-main-crate" }

#rs-ffi-interfaces = { path = "../../rs-ffi-macro/rs-ffi-interfaces" }
#rs-ffi-macro-derive = { path = "../../rs-ffi-macro/rs-ffi-macro-derive" }
[dev-dependencies]
libc = "0.2.146"
reqwest = { version = "0.11.18", features = ["blocking", "json"] }
serde = { version = "1.0.144", features = ["derive"] }
serde_json = "1.0.85"
dash-spv-masternode-processor = { path = "../dash-spv-masternode-processor", features = ["default", "test-helpers"] }

[build-dependencies]
cbindgen = "0.24.3"

[lib]
name = "dash_spv_apple_bindings"
crate-type = ["staticlib", "cdylib"]

#[profile.release]
#lto = "thin"
#opt-level = 3
##debug = true

