[package]
name = "dash_shared_core"
version = "0.1.1"
edition = "2018"
publish = false
build = "build.rs"

[dependencies]
[dependencies.dash_mndiff]
git = "https://github.com/dashevo/masternode-diff-processor"
branch = "dip-0024-tmp"
version = "0.1.0"
[dependencies.rs-merk-verify-c-binding]
git = "https://github.com/dashevo/rs-merk-verify-c-binding"
branch = "for-use-in-main-crate"
version = "0.1.3"

[build-dependencies]
cbindgen = "0.20.0"

[lib]
name = "dash_shared_core"
crate-type = ["staticlib", "cdylib"]

[profile.release]
lto = "thin"
opt-level = 3

