[package]
name = "dash_shared_core"
version = "0.2.8"
edition = "2021"
build = "build.rs"
publish = false

[dependencies]
[dependencies.dash-spv-masternode-processor]
git = "https://github.com/dashpay/masternode-diff-processor"
rev = "74200eb"

[dependencies.rs-merk-verify-c-binding]
git = "https://github.com/dashpay/rs-merk-verify-c-binding"
branch = "for-use-in-main-crate"
version = "0.1.3"

#[dependencies.dash-spv-masternode-processor]
#path = "../masternodes-diff-processor"


[build-dependencies]
cbindgen = "0.24.3"

[lib]
name = "dash_shared_core"
crate-type = ["staticlib", "cdylib"]

[profile.release]
lto = "thin"
opt-level = 3

